### ISSUE TITLE
IntelliJ doesn't recognize configuration

### ISSUE THREAD

**Issue by mwd410** [odavid/maven-plugins#7]
There seems to be some missing metadata describing configuration options, though it's a little unclear. IntelliJ highlights the entire `<mixins>` element red and says 'mixins is not allowed here'. Despite that, everything compiles and your plugin works exactly as expected. 

It actually recognizes `<indentSize>` and `<lineLength>` here, and ctrl+clicking on those brings me to a plugin.xml file that does not mention `mixins`. I'm on 0.1-alpha-38.

Am I doing something wrong? Thanks so much for the help!

```
<plugin>
  <groupId>com.github.odavid.maven.plugins</groupId>
  <artifactId>mixin-maven-plugin</artifactId>
  <extensions>true</extensions>
  <configuration>
    <mixins>
      <mixin>
        <groupId>com.company</groupId>
        <artifactId>boilerplate-svc</artifactId>
        <version>0.0-SNAPSHOT</version>
      </mixin>
    </mixins>
  </configuration>
</plugin>
```

**Comment by binkley** [comment]
Same issue.  In the plugin sources, I'm not finding the Mojo class I would expect for the plugin -- but that could be my own blindness.

**Comment by odavid** [comment]
Hi,
The mixin-maven-plugin is actually not a plugin, but a maven extension implemented as AbstractMavenLifecycleParticipant.

Declaring it as a plugin is a "dirty trick" (: I've made, since I (could not/would not/should not) extend the maven schema to support a mixin tag, but I had to pass the information to maven about which mixins to be merge into the pom. You can read it in [MixinsProjectLoader#loadConfiguration() method](https://github.com/odavid/maven-plugins/blob/master/mixin-maven-plugin/src/main/java/com/github/odavid/maven/plugins/MixinsProjectLoader.java). 

As for the intelliJ issue. I will try to see what I can.

Regards,
Ohad

**Comment by binkley** [comment]
I filed an issue on the IntelliJ side to match - https://youtrack.jetbrains.com/issue/IDEA-153323

**Comment by odavid** [comment]
Hi,
I am sorry for the late response. But I've been a bit busy these days.
I've fixed the issue using a fake mojo the adds the mixins element to the configuration. I think the IntelliJ ticket can be closed.
Regards,
Ohad
